### ISSUE TITLE
Line 196 in musica.py

### ISSUE THREAD

**Issue by douglaswinfield** [lafith/MUSICA#1]
The code crashes at line 196 in musica.py:  p is not an array.  
I think the line should be:
 np.divide(
                    np.abs(x), M), p))

Also, in demo.py - it's nice to show the results as well as save them:

img = plt.imread('0005.jpg')  # gray scale image
plt.figure()
plt.imshow(img,cmap='gray')

# run MUSICA:
rs = musica(img, L, params, plot=True)

plt.figure()
plt.imshow(rs,cmap='gray')
plt.show()
plt.imsave("contrast.jpg", rs, cmap='gray')

Otherwise, the program works well and does a great job in increasing contrast.

**Comment by lafith** [comment]
Thank you for pointing out that error. I have corrected that along with some modifications to demo.py to display and save the enhanced image.
Is there any other modifications required in your observation?

**Comment by douglaswinfield** [comment]
Yes, maybe one other change - You hard code L in demo.  You can calculate that value like this.   I pad the image and then calculate L

    row, col = img_pad.shape
    val = min(row, col)
    L = 1
    while val != 2:
        val = val / 2
        L += 1

**Comment by douglaswinfield** [comment]
Otherwise, this is a great algorithm I'm surprised OpenCV and Skimage don't have this built in.  Great work :)

**Comment by lafith** [comment]
I kept it like that because this algorithm depends on the selection of amplification values for each layer, hence the user should select a level of decomposition prior and create 'a' based on that.  Instead I think I will add a check on L after padding as there exists a limit for maximum level of decomposition.

And yes, even I was surprised at the result!. I am thinking about sending Skimage a pull request after some modifications.
